version: "3"

services:
  nginx:
    image: nginx:1.16.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/files/certificate.crt:/etc/nginx/ssl/certificate.crt:ro
      - ${PWD}/files/certificate.key:/etc/nginx/ssl/certificate.key:ro
      - ${PWD}/files/nginx.conf:/etc/nginx/nginx.conf:ro